spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres

encryption:
  secret: 12345

liquibase:
  enabled: true
  change-log: classpath:/db/migration/master.xml