spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "topSecret"
    expiration-ms: 86400000