paths:
  /api/cards/filter:
    get:
      summary: "Filter cards with pagination"
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: "Page number (starts from 0)"
        - in: query
          name: size
          schema:
            type: integer
          description: "Number of cards per page"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardFilterRequest"
      responses:
        200:
          description: "Filtered cards"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardResponse"
components:
  schemas:
    CardFilterRequest:
      type: object
      properties:
        status:
          type: string
          enum: [ ACTIVE, BLOCKED, EXPIRED ]
        ownerName:
          type: string
        expirationDateFrom:
          type: string
          format: date
        expirationDateTo:
          type: string
          format: date

openapi:
info: